from pulumi_gcp import compute
from config import NETWORK, REGION, SUBNET, IGW
from utils import resource_name     

def create_vpc():
    # Create a new VPC
    vpc = compute.Network(resource_name(NETWORK),
        name=resource_name(NETWORK), # Adding name=resource_name (RESOURCE_NAME) to each resource creation overrides random suffixes generated by Pulumi's auto-naming feature
        auto_create_subnetworks=False,
        description=f"{resource_name(NETWORK)} network",
    )

    # Create an Internet Gateway for the VPC
    igw = compute.GlobalAddress(resource_name(IGW),
        name=resource_name(IGW),
        description=f"{resource_name(IGW)} network",
    )

    # Create a Subnet within the VPC
    subnet = compute.Subnetwork(resource_name(SUBNET),
        name=resource_name(SUBNET),
        network=vpc.self_link,
        ip_cidr_range="10.0.0.0/16",
        region=REGION,
        description=f"{resource_name(SUBNET)} network",
    )

    return vpc, igw, subnet
